[build-system]
requires = [
  "setuptools==68.0.0",
  "setuptools-scm==7.1.0",
  "wheel",
]
build-backend = "setuptools.build_meta"

[project]
# To change to eager, or something similar
name = "metal_libs"
authors = [
    {name = "Tenstorrent"},
    {email = "info@tenstorrent.com"},
]
dependencies = [
  "pyyaml==5.3.1",
  "numpy==1.24.4",
  "loguru==0.6.0",
  "toolz==0.12.0",
  "matplotlib==3.7.1",
  "Pillow==9.5.0",
  "jupyterlab==4.0.7",
  "ipywidgets==8.1.1",

  # extra index required https://download.pytorch.org/whl/cpu
  "torch==2.2.1+cpu",
  "networkx==3.1",
  "torchtrail==0.0.18",
  "bokeh==3.1.1",

  # profiler
  "click==8.1.3",
  "dash==2.8.1",
  "pandas==1.5.3",
  "plotly==5.13.0",
  "seaborn==0.12.2",

  # gdb
  "rich==13.3.3",
  "pyelftools==0.29",
  "curtsies==0.4.1",
]
requires-python = ">=3.8"
description = "General compute framework for Tenstorrent devices"
dynamic = ["version"]

[tool.black]
line-length = 120
include = '^.*(ttnn|tests/scripts|tests/ttnn|tests/tt_eager/python_api_testing|tt_eager/tt_lib)/.*\.py$'

[tool.ruff]
line-length = 120
