name: "Build tt-metal artifacts"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-artifact:
    strategy:
      matrix:
        arch: ["grayskull", "wormhole_b0"]
    env:
      TT_METAL_ENV: ${{ vars.TT_METAL_ENV }}
      ARCH_NAME: ${{ matrix.arch }}
      CONFIG: ci
      SILENT: 0
    environment: dev
    runs-on: build
    steps:
      - uses: tenstorrent-metal/metal-workflows/.github/actions/checkout-with-submodule-lfs@v2.0.0
      - name: Set up dynamic env vars for build
        run: |
          echo "TT_METAL_HOME=$(pwd)" >> $GITHUB_ENV
      - name: Build tt-metal and libs
        run: |
          make build PYTHON_ENV=$HOME/python_env
          make tests
      - name: 'Tar files'
        run: tar -cvf ttm_${{ matrix.arch }}.tar build/hw build/lib tt_eager/tt_lib/*.so ttnn/ttnn/*.so build/programming_examples build/test
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: TTMetal_build_${{ matrix.arch }}
          path: ttm_${{ matrix.arch }}.tar
